INSERT INTO COMPANY (NAME) VALUES ('GMBh');
INSERT INTO COMPANY (NAME) VALUES ('K@PTA');

INSERT INTO MARKET (NAME) VALUES ('BMW');
INSERT INTO MARKET (NAME) VALUES ('KIA');
INSERT INTO MARKET (NAME) VALUES ('MINI');
INSERT INTO MARKET (NAME) VALUES ('VOLVO');

INSERT INTO SERVICE (NAME) VALUES ('Administrativas');
INSERT INTO SERVICE (NAME) VALUES ('Soporte tecnico');
INSERT INTO SERVICE (NAME) VALUES ('Diseño visual');
INSERT INTO SERVICE (NAME) VALUES ('Desarrollo de software');
INSERT INTO SERVICE (NAME) VALUES ('Consultoria');


