CREATE TABLE COMPANY (
	ID_COMPANY BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(128)
);

CREATE TABLE MARKET (
	ID_MARKET BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(128)
);

CREATE TABLE SERVICE (
	ID_SERVICE BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(128)
);

CREATE TABLE PROJECT (
	ID_PROJECT BIGINT PRIMARY KEY,
	NAME VARCHAR(128),
	DESCRIPTION VARCHAR(128),
	ID_COMPANY BIGINT,
	ID_MARKET BIGINT,
	ID_SERVICE BIGINT
);

CREATE TABLE TASK (
	ID_TASK BIGINT PRIMARY KEY,
	ID_PROJECT BIGINT,
	TITLE VARCHAR(128),
	TASK_GROUP_NAME VARCHAR(128)
);
